demo_locations = [
    {
        "location": "Shimla",
        "latitude": 31.1048,
        "longitude": 77.1734,
        "rainfall_mm": 185,
        "soil_moisture": 72,
        "slope_degree": 38,
        "elevation_m": 2206,
        "temperature_c": 18,
        "risk_score": 82,
        "risk_level": "High",
    },
    {
        "location": "Manali",
        "latitude": 32.2396,
        "longitude": 77.1887,
        "rainfall_mm": 240,
        "soil_moisture": 86,
        "slope_degree": 45,
        "elevation_m": 2050,
        "temperature_c": 15,
        "risk_score": 94,
        "risk_level": "Critical",
    },
    {
        "location": "Dehradun",
        "latitude": 30.3165,
        "longitude": 78.0322,
        "rainfall_mm": 120,
        "soil_moisture": 61,
        "slope_degree": 28,
        "elevation_m": 640,
        "temperature_c": 24,
        "risk_score": 58,
        "risk_level": "Moderate",
    },
    {
        "location": "Dharamshala",
        "latitude": 32.2190,
        "longitude": 76.3234,
        "rainfall_mm": 210,
        "soil_moisture": 78,
        "slope_degree": 41,
        "elevation_m": 1457,
        "temperature_c": 17,
        "risk_score": 76,
        "risk_level": "High",
    },
]