demo_locations = [
    {
        "location": "Itanagar",
        "state": "Arunachal Pradesh",
        "latitude": 27.0844,
        "longitude": 93.6053,
        "rainfall_mm": 0,
        "soil_moisture": 0,
        "slope_degree": 0,
        "elevation_m": 0,
        "temperature_c": 0,
        "risk_score": 0,
        "risk_level": "Low",
    },
    {
        "location": "Guwahati",
        "state": "Assam",
        "latitude": 26.1445,
        "longitude": 91.7362,
        "rainfall_mm": 0,
        "soil_moisture": 0,
        "slope_degree": 0,
        "elevation_m": 0,
        "temperature_c": 0,
        "risk_score": 0,
        "risk_level": "Low",
    },
    {
        "location": "Imphal",
        "state": "Manipur",
        "latitude": 24.8170,
        "longitude": 93.9368,
        "rainfall_mm": 0,
        "soil_moisture": 0,
        "slope_degree": 0,
        "elevation_m": 0,
        "temperature_c": 0,
        "risk_score": 0,
        "risk_level": "Low",
    },
    {
        "location": "Shillong",
        "state": "Meghalaya",
        "latitude": 25.5788,
        "longitude": 91.8933,
        "rainfall_mm": 0,
        "soil_moisture": 0,
        "slope_degree": 0,
        "elevation_m": 0,
        "temperature_c": 0,
        "risk_score": 0,
        "risk_level": "Low",
    },
    {
        "location": "Aizawl",
        "state": "Mizoram",
        "latitude": 23.7271,
        "longitude": 92.7176,
        "rainfall_mm": 0,
        "soil_moisture": 0,
        "slope_degree": 0,
        "elevation_m": 0,
        "temperature_c": 0,
        "risk_score": 0,
        "risk_level": "Low",
    },
    {
        "location": "Kohima",
        "state": "Nagaland",
        "latitude": 25.6751,
        "longitude": 94.1086,
        "rainfall_mm": 0,
        "soil_moisture": 0,
        "slope_degree": 0,
        "elevation_m": 0,
        "temperature_c": 0,
        "risk_score": 0,
        "risk_level": "Low",
    },
    {
        "location": "Gangtok",
        "state": "Sikkim",
        "latitude": 27.3389,
        "longitude": 88.6065,
        "rainfall_mm": 0,
        "soil_moisture": 0,
        "slope_degree": 0,
        "elevation_m": 0,
        "temperature_c": 0,
        "risk_score": 0,
        "risk_level": "Low",
    },
    {
        "location": "Agartala",
        "state": "Tripura",
        "latitude": 23.8315,
        "longitude": 91.2868,
        "rainfall_mm": 0,
        "soil_moisture": 0,
        "slope_degree": 0,
        "elevation_m": 0,
        "temperature_c": 0,
        "risk_score": 0,
        "risk_level": "Low",
    },
]